doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 120
autodetect: yes
requirements:
    - dev-requirements.txt
ignore-paths:
    - apps
    - sandbox
    - docs
    - pywinauto/unittests

pep257:
    disable:
        - D211  # conflicts with D203
